// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package server

import (
	"github.com/gin-gonic/gin"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for HealthResponseStatus.
const (
	Degraded  HealthResponseStatus = "degraded"
	Healthy   HealthResponseStatus = "healthy"
	Unhealthy HealthResponseStatus = "unhealthy"
)

// Defines values for ResponseCode.
const (
	CHECKFAILED       ResponseCode = "CHECK_FAILED"
	OK                ResponseCode = "OK"
	RATELIMITEXCEEDED ResponseCode = "RATE_LIMIT_EXCEEDED"
)

// Defines values for ServerInfoType.
const (
	Arcade ServerInfoType = "arcade"
	Mcp    ServerInfoType = "mcp"
)

// AccessHookRequest Access-hook request from engine to hook server
type AccessHookRequest struct {
	// Toolkits Map of a group of tools
	Toolkits Toolkits `json:"toolkits"`

	// UserId User ID
	UserId string `json:"user_id"`
}

// AccessHookResult Access-hook response from hook server to engine. If 'only' is included, ONLY those are allowed (deny list ignored).
type AccessHookResult struct {
	// Deny Map of a group of tools
	Deny *Toolkits `json:"deny,omitempty"`

	// Only Map of a group of tools
	Only *Toolkits `json:"only,omitempty"`
}

// Authorization Authorization information
type Authorization struct {
	// Oauth2 OAuth2 authorization details
	Oauth2 *OAuth2Details `json:"oauth2,omitempty"`

	// ProviderId ID of the OAuth provider
	ProviderId *string `json:"provider_id,omitempty"`
}

// ErrorResponse Error response from webhook server
type ErrorResponse struct {
	// Code Machine-readable error code for programmatic handling
	Code *string `json:"code,omitempty"`

	// Error Human-readable error message
	Error *string `json:"error,omitempty"`
}

// HealthResponse Health check response
type HealthResponse struct {
	// Status Health status
	Status *HealthResponseStatus `json:"status,omitempty"`
}

// HealthResponseStatus Health status
type HealthResponseStatus string

// OAuth2Details OAuth2 authorization details
type OAuth2Details struct {
	// At Access token claims (only present when token is a JWT; absent for opaque tokens)
	At *map[string]interface{} `json:"at,omitempty"`

	// Scopes OAuth scopes (always available from token response)
	Scopes *[]string `json:"scopes,omitempty"`

	// UserInfo User information from oauth2 provider
	UserInfo *map[string]interface{} `json:"user_info,omitempty"`
}

// PostHookOverride Override response parameters
type PostHookOverride struct {
	// Output Override the response returned
	Output *map[string]interface{} `json:"output,omitempty"`
}

// PostHookRequest Post-hook request from engine to hook server
type PostHookRequest struct {
	// Context Tool execution context
	Context ToolContext `json:"context"`

	// ExecutionCode Status code from the server
	ExecutionCode *string `json:"execution_code,omitempty"`

	// ExecutionError Execution error from the tool call
	ExecutionError *string `json:"execution_error,omitempty"`

	// ExecutionId Allows tracking requests and responses
	ExecutionId string `json:"execution_id"`

	// Inputs Tool inputs (name -> value)
	Inputs *map[string]interface{} `json:"inputs,omitempty"`

	// Output The execution output
	Output map[string]interface{} `json:"output"`

	// Server Server routing information
	Server ServerInfo `json:"server"`

	// Success Whether the tool succeeded
	Success *bool `json:"success,omitempty"`

	// Tool Tool identification information
	Tool ToolInfo `json:"tool"`
}

// PostHookResult Post-hook response from hook server to engine
type PostHookResult struct {
	// Code Response code from hook server
	Code ResponseCode `json:"code"`

	// ErrorMessage Error message for the Agent
	ErrorMessage *string `json:"error_message,omitempty"`

	// Override Override response parameters
	Override *PostHookOverride `json:"override,omitempty"`
}

// PreHookOverride Override execution parameters
type PreHookOverride struct {
	// Headers Override request headers
	Headers *map[string]string `json:"headers,omitempty"`

	// Inputs Override tool inputs
	Inputs *map[string]interface{} `json:"inputs,omitempty"`

	// Secrets Override secrets
	Secrets *[]map[string]string `json:"secrets,omitempty"`

	// Server Server routing information
	Server *ServerInfo `json:"server,omitempty"`
}

// PreHookRequest Pre-hook request from engine to hook server
type PreHookRequest struct {
	// Context Tool execution context
	Context ToolContext `json:"context"`

	// ExecutionId Allows tracking requests and responses
	ExecutionId string `json:"execution_id"`

	// Inputs Tool inputs (name -> value)
	Inputs map[string]interface{} `json:"inputs"`

	// Tool Tool identification information
	Tool ToolInfo `json:"tool"`
}

// PreHookResult Pre-hook response from hook server to engine
type PreHookResult struct {
	// Code Response code from hook server
	Code ResponseCode `json:"code"`

	// ErrorMessage Error message for the Agent
	ErrorMessage *string `json:"error_message,omitempty"`

	// Override Override execution parameters
	Override *PreHookOverride `json:"override,omitempty"`
}

// ResponseCode Response code from hook server
type ResponseCode string

// SecretRequirement Required secret definition
type SecretRequirement struct {
	// Name Secret name
	Name string `json:"name"`
}

// ServerInfo Server routing information
type ServerInfo struct {
	// Name Server name
	Name string `json:"name"`

	// Type Server type
	Type ServerInfoType `json:"type"`

	// Uri Server URI
	Uri string `json:"uri"`
}

// ServerInfoType Server type
type ServerInfoType string

// ToolAuthRequirements Authorization requirements for a tool
type ToolAuthRequirements struct {
	Oauth2 *struct {
		// Scopes Required scopes
		Scopes *[]string `json:"scopes,omitempty"`
	} `json:"oauth2,omitempty"`

	// ProviderId Provider ID
	ProviderId *string `json:"provider_id,omitempty"`

	// ProviderType Provider type
	ProviderType *string `json:"provider_type,omitempty"`
}

// ToolContext Tool execution context
type ToolContext struct {
	Authorization *[]Authorization `json:"authorization,omitempty"`

	// Metadata Arbitrary metadata from tool
	Metadata *map[string]interface{} `json:"metadata,omitempty"`

	// Secrets Required secrets (key only, no values)
	Secrets *[]string `json:"secrets,omitempty"`

	// UserId User ID for access checks
	UserId *string `json:"user_id,omitempty"`
}

// ToolInfo Tool identification information
type ToolInfo struct {
	// Name Tool name
	Name string `json:"name"`

	// Toolkit Toolkit name
	Toolkit string `json:"toolkit"`

	// Version Tool version
	Version string `json:"version"`
}

// ToolVersionInfo Version-specific information for a tool
type ToolVersionInfo struct {
	// Requirements Requirements for a toolkit (group of tools)
	Requirements *ToolkitRequirements `json:"requirements,omitempty"`

	// Version Tool version
	Version *string `json:"version,omitempty"`
}

// ToolkitInfo Information about a group of tools
type ToolkitInfo struct {
	// Tools Map of tool name to array of tool version info (there may be multiple versions of tools)
	Tools *map[string][]ToolVersionInfo `json:"tools,omitempty"`
}

// ToolkitRequirements Requirements for a toolkit (group of tools)
type ToolkitRequirements struct {
	// Authorization Authorization requirements for a tool
	Authorization *[]ToolAuthRequirements `json:"authorization,omitempty"`

	// Secrets Required secrets
	Secrets *[]SecretRequirement `json:"secrets,omitempty"`

	// Server Server routing information
	Server *ServerInfo `json:"server,omitempty"`
}

// Toolkits Map of a group of tools
type Toolkits map[string]ToolkitInfo

// AccessHookJSONRequestBody defines body for AccessHook for application/json ContentType.
type AccessHookJSONRequestBody = AccessHookRequest

// PostHookJSONRequestBody defines body for PostHook for application/json ContentType.
type PostHookJSONRequestBody = PostHookRequest

// PreHookJSONRequestBody defines body for PreHook for application/json ContentType.
type PreHookJSONRequestBody = PreHookRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Access control hook
	// (POST /access)
	AccessHook(c *gin.Context)
	// Health check endpoint
	// (GET /health)
	HealthCheck(c *gin.Context)
	// Post-execution hook
	// (POST /post)
	PostHook(c *gin.Context)
	// Pre-execution hook
	// (POST /pre)
	PreHook(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// AccessHook operation middleware
func (siw *ServerInterfaceWrapper) AccessHook(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AccessHook(c)
}

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.HealthCheck(c)
}

// PostHook operation middleware
func (siw *ServerInterfaceWrapper) PostHook(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostHook(c)
}

// PreHook operation middleware
func (siw *ServerInterfaceWrapper) PreHook(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PreHook(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/access", wrapper.AccessHook)
	router.GET(options.BaseURL+"/health", wrapper.HealthCheck)
	router.POST(options.BaseURL+"/post", wrapper.PostHook)
	router.POST(options.BaseURL+"/pre", wrapper.PreHook)
}
